apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
    containers:
    - name: nginx
      image: nginx:alpine
      imagePullPolicy: Always
      env:
      - name: HOGE
        value: hoge
      ports:
      - containerPort: 80
        protocol: TCP
      workingDir: /tmp
