apiVersion: v1
kind: PersistentVolume
metadata:
    name: lazy
spec:
    storageClassName: lazy
    capacity:
        storage: 1Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    hostPath:
        path: /data/lazy
        type: DirectoryOrCreate    