apiVersion: v1
kind: PersistentVolume
metadata:
    name: slow
spec:
    storageClassName: slow
    capacity:
        storage: 1Gi
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    hostPath:
        path: /data/slow
        type: DirectoryOrCreate