apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: standard
spec:
    storageClassName: standard
    resources:
        requests:
            storage: 1Gi
    accessModes:
    - ReadWriteOnce