apiVersion: v1
kind: Pod
metadata:
    name: env
spec:
    containers:
    - name: alpine
      image: alpine
      command: ["tail", "-f", "/dev/null"]
      env:
      - name: HOGE
        valueFrom:
            configMapKeyRef:
                name: cm
                key: HOGE
      - name: PASS
        valueFrom:
            secretKeyRef:
                name: secret
                key: password
                optional: true
      envFrom:
      - configMapRef:
          name: cm
      - secretRef:
          name: secret
        prefix: SEC_