apiVersion: v1
kind: Pod
metadata:
    name: value
spec:
    containers:
    - name: alpine
      image: alpine
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
      - name: cm
        mountPath: /cm
      - name: secret
        mountPath: /secret
      - name: secret2
        mountPath: /secret2
    volumes:
    - name: cm
      configMap:
        name: cm
    - name: secret
      secret:
        secretName: secret
    - name: secret2
      secret:
        secretName: secret
        defaultMode: 0600
        items:
        - key: cred.txt
          path: creds/secret.txt
          mode: 0400
    terminationGracePeriodSeconds: 0