apiVersion: v1
kind: Pod
metadata:
    name: fsgroup
spec:
    containers:
    - name: alpine
      image: alpine
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
      - name: data
        mountPath: /data
    securityContext:
        fsGroup: 1000
    volumes:
    - name: data
      emptyDir:
    terminationGracePeriodSeconds: 0