apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        requests:
            cpu: 50m
            memory: 8Mi
        limits:
            cpu: 200m
            memory: 64Mi