apiVersion: v1
kind: Pod
metadata:
    name: nginx
    labels:
        name: nginx
        env: dev
    annotations:
        version: '1'
spec:
    containers:
    - name: nginx
      image: nginx
    nodeSelector:
        env: dev