apiVersion: v1
kind: Pod
metadata:
    name: date-tail
spec:
    initContainers:
    - name: touch
      image: alpine
      command: ["sh", "-c"]
      args:
      - |
        echo Initialize at `date`
        touch /var/log/date-tail/output.log
      volumeMounts:
      - name: log-volume
        mountPath: /var/log/date-tail
    containers:
    - name: date
      image: alpine
      command: ["sh", "-c"]
      args:
      - |
        echo Append log at `date`
        exec >> /var/log/date-tail/output.log
        echo -n 'Start at: '
        while true
        do
        date
        sleep 1
        done
      volumeMounts:
      - name: log-volume
        mountPath: /var/log/date-tail
    - name: tail
      image: alpine
      command: ["sh", "-c"]
      args:
      - |
       echo Following log at `date`
       tail -f /var/log/date-tail/output.log
      volumeMounts:
      - name: log-volume
        mountPath: /var/log/date-tail
    volumes:
    - name: log-volume
      emptyDir:
    terminationGracePeriodSeconds: 0
