apiVersion: v1
kind: Pod
metadata:
    name: nginx-readiness-probe
    labels:
        app: nginx
spec:
    containers:
    - name: nginx
      image: nginx
      readinessProbe:
        httpGet:
            path: /
            port: 80
        periodSeconds: 1
        failureThreshold: 1