apiVersion: v1
kind: Pod
metadata:
    name: nginx-liveness-probe
spec:
    containers:
    - name: nginx
      image: nginx
      livenessProbe:
        httpGet:
            path: /
            port: 80
        periodSeconds: 5
        failureThreshold: 5