apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
    affinity:
        podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - memcached
              topologyKey: kubernetes.io/hostname
    containers:
    - name: nginx
      image: nginx