apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
    containers:
    - name: nginx
      image: nginx
    tolerations:
    - key: taint
      operator: Equal
      value: hoge
      effect: NoSchedule