apiVersion: v1
kind: Pod
metadata:
    name: guaranteed
spec:
    containers:
    - name: nginx
      image: nginx
      resources:
        limits:
            cpu: 100m
            memory: 64Mi
        requests:
            cpu: 100m
            memory: 64Mi