apiVersion: v1
kind: LimitRange
metadata:
    name: limits
spec:
    limits:
    - type: Pod
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 50m
        memory: 4Mi
    - type: Container
      max:
        cpu: 200m
        memory: 128Mi
      min:
        cpu: 50m
        memory: 4Mi
      default:
        cpu: 100m
        memory: 64Mi
      defaultRequest:
        cpu: 100m
        memory: 32Mi