apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 5
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx
              resources:
                requests:
                    cpu: 100m
                    memory: 8Mi
    