apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    strategy:
        rollingUpdate:
            maxSurge: 50%
            maxUnavailable: 0%
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: nginx
              image: nginx:alpine
    