apiVersion: batch/v1beta1
kind: CronJob
metadata:
    name: sleep
spec:
    schedule: '*/1 * * * *'
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                    - name: sleep
                      image: alpine
                      command: ["sh", "-c"]
                      args:
                      - |
                        sleep 5
                    restartPolicy: Never